ALTER TABLE events ADD COLUMN heads_up_at TIMESTAMPTZ;
ALTER TABLE events ADD COLUMN heads_up_sent BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE events ADD COLUMN delay_start_at TIMESTAMPTZ;
ALTER TABLE events ADD COLUMN delay_end_at TIMESTAMPTZ;
